api: https://122e4e-mapbox.global.ssl.fastly.net/core
baseApi: https://122e4e-mapbox.global.ssl.fastly.net
tileApi: https://cloudfront-staging.tilestream.net
accessToken: pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpZ3BqeDZlcDAwMDBzcmt1YnQ1OTM4cTEifQ.54XwgUSkvlmB7gHW4vWJ3w
url: https://www.mapbox.com
versions:
  - 2.1
  - 2.0
  - 1.0.1
  - 1.0.0
spec_url: https://github.com/mapbox/vector-tile-spec/
version_url: https://github.com/mapbox/vector-tile-spec/tree/master/
current: 2.1
permalink: /:categories/:title
baseurl: /vector-tiles
