url: https://www.mapbox.com
versions:
  - 2.1
  - 2.0
  - 1.0.1
  - 1.0.0
spec_url: https://github.com/mapbox/vector-tile-spec/
version_url: https://github.com/mapbox/vector-tile-spec/tree/master/
current: 2.1
permalink: /:categories/:title
baseurl: /vector-tiles
